### ISSUE TITLE
Bootstrap "compatibility"

### ISSUE THREAD

**Issue by xxvii** [JeremiePat/grids-and-rulers#1]
Hello,
if I want to replicate the exact grid defined by Boostrap 4, the left gutter width on first column and right gutter width on last column should be half the width set in the options.

It would be also useful to have a separator between columns:

Something like this... http://grid.mindplay.dk/#[[0,0,0,0,0,0,0],['Verdana','','','','','',''],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[1,2,2,2,2,2,2],[10,16,16,16,16,16,16],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[12,30,16,15,1140],{},[0,1]]

...to replicate Bootstrap 4 grid: https://getbootstrap.com/docs/4.1/layout/grid/#grid-options

**Comment by JeremiePat** [comment]
Hi! Sorry for the very long delay. [Version 2.0](https://github.com/JeremiePat/grids-and-rulers/tree/v2) is on its way and it will change the way to configure the grids. It will be very closer than what you are asking for.
