### ISSUE TITLE
Grids are not persistent

### ISSUE THREAD

**Issue by edwinbradford** [JeremiePat/grids-and-rulers#3]
This is by far the best grid layout tool I've found in the Chrome store. Grids do not appear to be saved between sessions. When I relaunch Chrome I have to create the grid again. Not sure if this is as designed, a limitation of Chrome or a bug.

**Comment by JeremiePat** [comment]
Good catch! [Version 2.0](https://github.com/JeremiePat/grids-and-rulers/tree/v2) is on its way and fix that problem.
